/************************************************************************************
 US211553: Evaluation of sip.js by implementing a B2BUA
*************************************************************************************
 Description :  This file represent the basic configuration file for thr B2BUA server
 Author      :  Samir Kumar Behera
 Date        :  01/25/2014
*************************************************************************************/

/* Set the localhost, outbound proxy and sipport to be used for the B2BUA server
 *  Locahost shall be used in the contact header being generated by the B2BUA
 *  server and is essential in call routing
 */
module.exports = {
    development: {
        sipport: 5060,
        outboundproxy: '192.168.0.1',
        domain: 'example.com',
        //ip and host of the machine the this is running on
        localhost: '192.168.0.1:5060'
    }
};

